#+TITLE: Schmeep
#+SUBTITLE: Chibi Scheme Bluetooth REPL for Android

* Features

Schmeep is an Android app that combines:

- *R7RS Scheme*: embedded [[https://synthcode.com/scheme/chibi/][Chibi Scheme]] interpreter
- *Bluetooth SPP REPL*: Remote Scheme REPL (Read-Eval-Print Loop) via
  Bluetooth Serial Port Profile.  Uses a command-line program for I/O.
- *WebView-Only UI*: full-screen WebView for user interface
- *JavaScript-to-Native Bridge*: JavaScript-to-JNI communication for
  Scheme evaluation

* Demo video

https://github.com/user-attachments/assets/2158edab-2e02-4f8c-a2da-103a7c11e484

* Talk

I gave a lightning talk about Schmeep at the BALISP (Bay Area Lisp and Scheme)
meeting on 3 Nov 2025:

https://www.youtube.com/watch?v=YlmrYAyJxdE

The demo video above was supposed to be included, but I ended up not
being able to show it for technical reasons.

* Credit

Thanks to Nawal Husnoo, author of [[https://github.com/husnoo/chibi-droid/][chibi-droid]], and cnlohr, author of
[[https://github.com/cnlohr/rawdrawandroid][rawdrawandroid]], for inspiration.

* Testing

The command-line client can be tested with an =expect= script.

First, build the client:

#+BEGIN_SRC sh
make schmeep
#+END_SRC

Then run the test script.  You will need to have the =expect= program
installed.

#+BEGIN_SRC sh
tests/schmeep.expect
#+END_SRC

The script will connect to the Schmeep Android app, send some Scheme
expressions, and test for correct evaluation.  It also checks that
interrupts (Ctrl-C) are handled correctly.  It will then disconnect,
connect again, and test for correct evaluation.  It will display "ALL
PASSED" at the end iff all tests pass.
